matching-manager/matching-manager

app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
=> [Test] : test용 커밋

app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
=> [fix] homefragment

app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
=> [Merge] test4

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/matching_manager/data/model/ArenaResponse.kt, app/src/main/java/com/example/matching_manager/data/remote/ArenaRemoteDataSource.kt, app/src/main/java/com/example/matching_manager/data/repository/ArenaRepositoryImpl.kt, app/src/main/java/com/example/matching_manager/domain/model/ArenaEntity.kt, app/src/main/java/com/example/matching_manager/domain/model/modelMapper.kt, app/src/main/java/com/example/matching_manager/domain/usecase/GetArenaInfoUseCase.kt, app/src/main/java/com/example/matching_manager/retrofit/AuthorizationInterceptor.kt, app/src/main/java/com/example/matching_manager/retrofit/RetrofitClient.kt, app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaActivity.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaListAdapter.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModel.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModelFactory.kt, app/src/main/java/com/example/matching_manager/util/Utils.kt, app/src/main/res/layout/arena_activity.xml, app/src/main/res/values/kakao_api_key.xml
- 입력한 위치의 위도 경도값 찾는기능 구현
- 위도경도 바탕으로 API Response 받아와 rv에 띄우기
- [Fix] : region 형식 수정
- [Fix] : recyclerview list안뜨던 문제 해결
.close #25
=> [Merge] 입력한 주소의 위도경도 받아와 API 통신

app/build.gradle, app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamCalender.kt, app/src/main/res/drawable/button_off.xml, app/src/main/res/drawable/button_on.xml, app/src/main/res/drawable/toggle_selector.xml, app/src/main/res/layout/age_picker.xml, app/src/main/res/layout/team_add_activity.xml, app/src/main/res/layout/team_calender.xml, app/src/main/res/layout/team_detail_activity.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/string_area.xml, app/src/main/res/values/string_level.xml, app/src/main/res/values/string_time.xml, app/src/main/res/values/string_type.xml, app/src/main/res/values/strings.xml
=> [Merge] team fragment spinner 구현

app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchListAdapter.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchRepository.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchRepositoryImpl.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchViewModel.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchViewModelFactory.kt
data layer로 구조 변경하였습니다.
.close #37
=> [Merge] : MVVM을 위한 data layer 변경

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaActivity.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaListAdapter.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModel.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/detail_dialog/ArenaDetailFragment.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/detail_dialog/ArenaDetailViewModel.kt, app/src/main/java/com/example/matching_manager/util/Utils.kt, app/src/main/res/drawable/btn_background_green_fill.xml, app/src/main/res/drawable/btn_background_green_stroke.xml, app/src/main/res/drawable/btn_background_white.xml, app/src/main/res/drawable/dialog_radius_background.xml, app/src/main/res/drawable/ic_call.xml, app/src/main/res/layout/activity_team_list_adapter.xml, app/src/main/res/layout/activity_team_view_model.xml, app/src/main/res/layout/arena_detail_fragment.xml, app/src/main/res/layout/home_fragment.xml, app/src/main/res/layout/match_detail_activity.xml, app/src/main/res/layout/team_add_activity.xml, app/src/main/res/layout/team_detail_activity.xml, app/src/main/res/values/strings.xml
- DialogFragment 구현
- DialogFragment UI 디자인 작업
- 전화걸기 기능 구현
- URL 공유기능 구현
- ArenaSharedViewModel
- custom Btn 디자인 작업
.close #39
=> [Merge] : Arena detail 작업

app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamItem.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt, app/src/main/java/com/example/matching_manager/ui/team/view/TeamViewModel.kt, app/src/main/res/layout/team_fragment.xml, app/src/main/res/values/string_type.xml, app/src/main/res/values/strings.xml
=> [MERGE]Refactoring/my code

app/src/main/java/com/example/matching_manager/ui/match/MatchDataModel.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt, app/src/main/java/com/example/matching_manager/ui/my/MyDeleteDialog.kt, app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt, app/src/main/java/com/example/matching_manager/ui/my/MyMatchDataModel.kt, app/src/main/java/com/example/matching_manager/ui/my/MyMatchEditActivity.kt, app/src/main/java/com/example/matching_manager/ui/my/MyMatchRepository.kt, app/src/main/java/com/example/matching_manager/ui/my/MyMatchRepositoryImpl.kt, app/src/main/java/com/example/matching_manager/ui/my/MyViewModel.kt, app/src/main/res/values/strings.xml
매치 게시글 수정 및 삭제 시 화면 갱신 오류 해결 하고 MyPage 게시글 필터링 하도록 하였습니다
=> [MERGE] 매치 게시글 수정 및 삭제 시 화면 갱신 오류 해결

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/matching_manager/ui/match/MatchDataModel.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt, app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt, app/src/main/java/com/example/matching_manager/ui/my/MyMatchDataModel.kt, app/src/main/java/com/example/matching_manager/ui/my/MyMatchDetailActivity.kt, app/src/main/java/com/example/matching_manager/ui/my/MyMatchEditActivity.kt, app/src/main/res/layout/match_detail_activity.xml, app/src/main/res/layout/match_fragment.xml, app/src/main/res/layout/match_writing_activity.xml, app/src/main/res/layout/my_fragment.xml, app/src/main/res/layout/my_match_detail_activity.xml
매치 리스트 및 글 작성 시 세부 기능 추가
.close #64
=> [Merge] 매치 리스트 및 글 작성 시 세부 기능 추가

app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamItem.kt, app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAddCategory.kt, app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamFilterCategory.kt, app/src/main/java/com/example/matching_manager/ui/team/view/TeamViewModel.kt, app/src/main/res/layout/team_detail_activity.xml, app/src/main/res/layout/team_filter_category.xml, app/src/main/res/values/string_spinner.xml
=> [MERGE] Feat/teamfragment filter

app/src/main/java/com/example/matching_manager/data/repository/GeoRepositoryImpl.kt, app/src/main/java/com/example/matching_manager/domain/repository/GeoRepository.kt, app/src/main/java/com/example/matching_manager/domain/usecase/geo/GetGeoLocationUseCase.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModel.kt, app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModelFactory.kt, app/src/main/java/com/example/matching_manager/util/Utils.kt
1. Util에 있던 경도 위도 받아오는 Geocoding을 데이터 Layer로 이동
2. Repository facade pattern 구성
3. DoaminLayer GetGeoLocationUseCase 구현
4. ArenaViewModelFactory를 통해 Usecase 주입
5. ArenaViewModel에서 경도 위도값 처리 코드 수정
.close #68
=> [Merge] Refactoring/GeoCoding to MVVM

app/build.gradle, app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
=> [Feat] : 글 작성시 빈칸이 있으면 예외처리

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/matching_manager/ui/match/MatchDataModel.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchSharedViewModel.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt, app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchCalender.kt, app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchFilterCategory.kt, app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchNumber.kt, app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchSortBottomSheet.kt, app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchTime.kt, app/src/main/java/com/example/matching_manager/ui/my/MyMatchEditActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamWritingActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAddCategory.kt, app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAge.kt, app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamTime.kt, app/src/main/res/layout/match_calender.xml, app/src/main/res/layout/match_filter_category.xml, app/src/main/res/layout/match_number.xml, app/src/main/res/layout/match_time.xml, app/src/main/res/layout/match_writing_activity.xml, app/src/main/res/layout/my_match_edit_activity.xml, app/src/main/res/layout/team_writing_activity.xml
=> [MERGE] Feature/team match add page edit

app/src/main/java/com/example/matching_manager/ui/match/MatchDeletedAlertDialog.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchViewModel.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt, app/src/main/res/layout/match_deleted_alert_dialog.xml
=> [Merge] : 삭제된 게시물 클릭 시 접근 제한 다이얼로그 표시

app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchNumber.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamWritingActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAge.kt, app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamNumber.kt, app/src/main/java/com/example/matching_manager/ui/team/viewmodel/TeamViewModel.kt, app/src/main/res/layout/match_writing_activity.xml, app/src/main/res/layout/team_writing_activity.xml, app/src/main/res/values/string_spinner.xml
-팀 프래그먼트 필터기능에 버튼 클릭과 필터에 맞게 데이터를 뿌려주도록 수정하였습니다.
- 바텀리스트 xml을 수정하였습니다.
- 팀 페이지
- 매치 페이지
close #102
=> 팀 프래그먼트 필터기능 수정

app/src/main/java/com/example/matching_manager/ui/match/MatchDataModel.kt, app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/TeamWritingActivity.kt, app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAge.kt, app/src/main/res/layout/match_writing_activity.xml, app/src/main/res/layout/team_writing_activity.xml
- 팀 글작성 페이지 예외처리 
- 매치 글작성 페이지 예외처리
TeamWrithingFragment.kt
MatchWrithingFragment.kt
=> 매치,팀 페이지 글작성 예외처리

app/build.gradle, app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarEditDialogFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarMemoDecorator.kt, app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarViewModel.kt, app/src/main/res/layout/calendar_add_dialog_fragment.xml, app/src/main/res/layout/calendar_edit_dialog_fragment.xml, app/src/main/res/layout/calendar_fragment.xml, app/src/main/res/values/string_spinner.xml, app/src/main/res/values/strings.xml
##주요변동 페이지
calendareditfragment  
스팬 기능 수정
editfragment ui 날짜 edittext 삭제
calendareditfragment ui 수정
calendareditfragment 기능 수정
close #126
=> [Fix] 캘린더에딧프래그먼트 기능 수정

app/src/main/AndroidManifest.xml, app/src/main/java/com/link_up/matching_manager/ui/home/home/AnnouncementActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/AnnouncementDataModel.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/AnnouncementDetailActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/AnnouncementFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/AnnouncementListAdapter.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/HomeAnnouncementListAdapter.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/HomeFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/HomeMatchListAdapter.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/HomeViewModel.kt, app/src/main/java/com/link_up/matching_manager/ui/match/MatchDetailActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/bookmark/MyBookmarkApplicationFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/my/bookmark/MyBookmarkRecruitFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchEditActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationEditActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitEditActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/team/TeamDetailActivity.kt, app/src/main/res/drawable/ic_cancel_image.xml, app/src/main/res/layout/announcement_activity.xml, app/src/main/res/layout/announcement_detail_activity.xml, app/src/main/res/layout/announcement_fragment.xml, app/src/main/res/layout/announcement_item.xml, app/src/main/res/layout/home_fragment.xml, app/src/main/res/layout/home_recyclerview_item_match.xml, app/src/main/res/layout/my_match_edit_activity.xml, app/src/main/res/layout/my_team_application_edit_activity.xml, app/src/main/res/layout/my_team_recruit_edit_activity.xml
용병 관심 목록 기능 오류 수정
글 수정 시 기존 데이터 불러오기
홈 화면 매치 리스트 및 공지 리스트 기능
전체 공지 화면 기능
UI/home 전체
close #129
=> 용병 관심 목록 기능 오류 수정, 글 수정 시 기존 데이터 불러오기, 홈 화면 매치 리스트 및 공지 리스트 기능, 전체 공지 화면 기능

app/src/main/java/com/link_up/matching_manager/data/repository/database/UserInfoRepositoryImpl.kt, app/src/main/java/com/link_up/matching_manager/ui/fcm/send/SendFcmFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/match/MatchDetailActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/match/MatchViewModel.kt, app/src/main/java/com/link_up/matching_manager/ui/match/MatchWritingActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/my/MyFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/my/my/MyViewModel.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/signin/SignInSharedViewModel.kt, app/src/main/java/com/link_up/matching_manager/ui/team/TeamDetailActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/team/TeamWritingActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/team/view_model/TeamViewModel.kt, app/src/main/java/com/link_up/matching_manager/util/UserInformation.kt, app/src/main/res/layout/send_fcm_fragment.xml, app/src/main/res/values/strings.xml
- 메시지가 자동으로 id, number을 포함하게 구현
- SendFcm 페이지
=> 매칭/용병 신청 시 메시지가 자동으로 id, number을 포함하게 구현

app/src/main/java/com/link_up/matching_manager/ui/home/home/AnnouncementFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/HomeFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/home/home/HomeViewModel.kt, app/src/main/java/com/link_up/matching_manager/ui/main/MainActivity.kt, app/src/main/res/layout/announcement_detail_activity.xml
홈 매치 더보기 버튼 클릭 시 매치 탭 이동
공지사항 클릭 시 해당 공지사항 세부 내용 다이얼로그 띄우기
##주요 페이지
HomeFragment
AnnouncementFragment
MainActivity
=> 홈 화면 기능 마무리

app/src/main/java/com/link_up/matching_manager/data/repository/SharedPreferenceRepositoryImpl.kt, app/src/main/java/com/link_up/matching_manager/data/repository/database/UserInfoRepositoryImpl.kt, app/src/main/java/com/link_up/matching_manager/domain/repository/SharedPreferenceRepository.kt, app/src/main/java/com/link_up/matching_manager/domain/usecase/sharedpreference/DeleteUserTypeUseCase.kt, app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarAddDialogFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/fcm/send/SendFcmFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/main/MainActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/match/MatchDetailActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/bookmark/MyBookmarkApplicationFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/my/bookmark/MyBookmarkMatchFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/my/bookmark/MyBookmarkRecruitFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchEditActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/my/MyDeleteDialog.kt, app/src/main/java/com/link_up/matching_manager/ui/my/my/MyFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/my/my/MyPostViewModel.kt, app/src/main/java/com/link_up/matching_manager/ui/my/my/MyPostViewModelFactory.kt, app/src/main/java/com/link_up/matching_manager/ui/my/my/MyViewModel.kt, app/src/main/java/com/link_up/matching_manager/ui/my/my/MyViewModelFactory.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationDeleteDialog.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationEditActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitDeleteDialog.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitEditActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/signin/SignInActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/signin/SignInFragment.kt, app/src/main/java/com/link_up/matching_manager/ui/team/TeamDetailActivity.kt, app/src/main/res/layout/my_fragment.xml
- 알림 Body Int값으로 가는 오류 수정
- 뒤로가기 오류 수정
- lateinit 초기화 오류 수정
- Ui 짤리는 부분 수정
- 달력 fatal 오류 예외처리
- 유저 로그아웃 기능 재구현
=> 전반적인 오류 수정

app/src/main/java/com/link_up/matching_manager/ui/main/MainActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchEditActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationEditActivity.kt, app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitEditActivity.kt
용병 신청 수정 페이지 상단 문구 수정
처음 앱 시작 시 탭 클릭 후 비정상 페이지 이동 버그 수정
게시글 수정 시 사진 없어지는 버그 수정
탭 레이아웃 Calender텍스트 잘림 수정
MainActivity
MyMatch, MyTeamEditActivity
=> 용병 신청 수정 페이지 상단 문구 수정, 처음 앱 시작 시 탭 클릭 후 비정상 페이지 이동 버그 수정, 게시글 수정 시 사진 없어지는 버그 수정, 탭 레이아웃 Calender텍스트 잘림 수정
